<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "til_application"
 *
 * Auto generated by Extension Builder 2016-02-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TIL Online Bewerbungsformular',
	'description' => 'A formula to fill in all data for a application for a TIL scholarship',
	'category' => 'plugin',
	'author' => 'Manfred Ursprung',
	'author_email' => 'manfred@manfred-ursprung.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.5.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);